### ISSUE TITLE
Elements disappear

### ISSUE THREAD

**Issue by jaydens** [karlhorky/gray#12] opened 2014-06-05 15:40 UTC
Hi,

Plugin works fine in Chrome & Chrome Canary but in Firefox and Safari the elements disappear after the page has loaded as if they are not there.

Please see the images attached - hopefully you can help
![screenshot 2014-06-03 16 00 36](https://cloud.githubusercontent.com/assets/5781767/3161859/f45c3af6-eb2f-11e3-9776-621745dab9c9.png)
![screenshot 2014-06-03 16 00 48](https://cloud.githubusercontent.com/assets/5781767/3161860/f45c81dc-eb2f-11e3-955e-ba65a5d442f3.png)

The original code looked like this; 
<li class="grayscale grayscale-fade">
      <a href="/index.php?a=showDetails&amp;m=club&amp;v=43&amp;i=5">
            <img class="club maglogo" src="./static_images/ogos/club.png">
            <img class="club magcover" src="./static_images/club/1.jpg">
            
            <img class="actionnow">
       </a>
</li>

It seems to have removed the images completly however it works fine in Chrome / Safari 
The first screenshot - the blue box is me hovering over the element in Firebug showing that it is there but not there somehow :confounded: 

Thanks!

**Comment by karlhorky** [comment] 2014-06-10 15:59
Does it help to set a width and height on the images?

If not, can you please provide a failing demo on JSFiddle / CodePen / JS Bin?

**Comment by karlhorky** [comment] 2014-07-16 15:15
Closing this since I cannot reproduce. Let me know if you set up a failing demo and I can take another look.

**Closed as completed by karlhorky** 2014-07-16 15:15 UTC
